name: Laravel

on:
  
  push:
      branches: [ "master", "develop" ]
  pull_request:
      branches: [ "master", "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
     

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Change this to your desired PHP version

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install dependencies
      run: composer install

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    - name: Check test status
      if: ${{ failure() }}
      continue-on-error: true
      run: echo "Unit tests failed. Please fix the issues before merging the pull request."



    - name: Deploy to cPanel
      uses: appleboy/scp-action@master
      with:
        host: 192.185.143.201
        username: ${{ secrets.CPANEL_USERNAME }} 
        password: ${{ secrets.CPANEL_PASSWORD }} 
        source: "path/to/your/build"
        target: "public_html"


      